services:
  career-db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: career-db
    image: hicsail/career-db-backend:unstable
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ../../stack.env