export const formats = [
    "Toolkit/Activity",
    "Findings/Analysis",
    "PPT (Editable)",
    "PPT (PDF)",
    "Paper (PDF)",
    "Policy Brief",
    "Resource Brief",
    "Website",
    "Information Brief",
    "Dashboard",
    "Guide",
    " Handbook",
    "Report",
    "Webinar",
    "Information (PDF)",
    "Information (Editable)",
    "Practice Brief",
    "Research",
    "Journal Article (PDF)",
    "B\"&\"ook/Chapter (PDF)",
    "Article (PDF)",
    "Video",
    "Book",
    "Remarks"
]